# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 514)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout.setSpacing(16)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftLayout = QtWidgets.QVBoxLayout()
        self.leftLayout.setSpacing(20)
        self.leftLayout.setObjectName("leftLayout")
        self.parametersFrame = QtWidgets.QFrame(self.centralwidget)
        self.parametersFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.parametersFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.parametersFrame.setLineWidth(1)
        self.parametersFrame.setObjectName("parametersFrame")
        self.parametersLayout = QtWidgets.QVBoxLayout(self.parametersFrame)
        self.parametersLayout.setSpacing(8)
        self.parametersLayout.setObjectName("parametersLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_14 = QtWidgets.QLabel(self.parametersFrame)
        self.label_14.setMinimumSize(QtCore.QSize(160, 16))
        self.label_14.setMaximumSize(QtCore.QSize(200, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(16)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.parametersFrame)
        self.label.setMinimumSize(QtCore.QSize(160, 16))
        self.label.setMaximumSize(QtCore.QSize(200, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.widthSpinBox = QtWidgets.QSpinBox(self.parametersFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widthSpinBox.sizePolicy().hasHeightForWidth())
        self.widthSpinBox.setSizePolicy(sizePolicy)
        self.widthSpinBox.setMinimumSize(QtCore.QSize(80, 24))
        self.widthSpinBox.setMaximumSize(QtCore.QSize(112, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.widthSpinBox.setFont(font)
        self.widthSpinBox.setWrapping(False)
        self.widthSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.widthSpinBox.setProperty("showGroupSeparator", True)
        self.widthSpinBox.setMinimum(1)
        self.widthSpinBox.setMaximum(100000)
        self.widthSpinBox.setProperty("value", 1000)
        self.widthSpinBox.setObjectName("widthSpinBox")
        self.horizontalLayout_2.addWidget(self.widthSpinBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(16)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.parametersFrame)
        self.label_3.setMinimumSize(QtCore.QSize(160, 16))
        self.label_3.setMaximumSize(QtCore.QSize(200, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.heightSpinBox = QtWidgets.QSpinBox(self.parametersFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heightSpinBox.sizePolicy().hasHeightForWidth())
        self.heightSpinBox.setSizePolicy(sizePolicy)
        self.heightSpinBox.setMinimumSize(QtCore.QSize(80, 24))
        self.heightSpinBox.setMaximumSize(QtCore.QSize(112, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.heightSpinBox.setFont(font)
        self.heightSpinBox.setWrapping(False)
        self.heightSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.heightSpinBox.setProperty("showGroupSeparator", True)
        self.heightSpinBox.setMinimum(1)
        self.heightSpinBox.setMaximum(100000)
        self.heightSpinBox.setProperty("value", 500)
        self.heightSpinBox.setObjectName("heightSpinBox")
        self.horizontalLayout_5.addWidget(self.heightSpinBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(16)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.parametersFrame)
        self.label_4.setMinimumSize(QtCore.QSize(160, 16))
        self.label_4.setMaximumSize(QtCore.QSize(200, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.thicknessSpinBox = QtWidgets.QSpinBox(self.parametersFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thicknessSpinBox.sizePolicy().hasHeightForWidth())
        self.thicknessSpinBox.setSizePolicy(sizePolicy)
        self.thicknessSpinBox.setMinimumSize(QtCore.QSize(80, 24))
        self.thicknessSpinBox.setMaximumSize(QtCore.QSize(112, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.thicknessSpinBox.setFont(font)
        self.thicknessSpinBox.setWrapping(False)
        self.thicknessSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.thicknessSpinBox.setProperty("showGroupSeparator", True)
        self.thicknessSpinBox.setMinimum(1)
        self.thicknessSpinBox.setMaximum(1000)
        self.thicknessSpinBox.setProperty("value", 4)
        self.thicknessSpinBox.setObjectName("thicknessSpinBox")
        self.horizontalLayout_6.addWidget(self.thicknessSpinBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.parametersLayout.addLayout(self.verticalLayout_5)
        self.line = QtWidgets.QFrame(self.parametersFrame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.parametersLayout.addWidget(self.line)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_15 = QtWidgets.QLabel(self.parametersFrame)
        self.label_15.setMinimumSize(QtCore.QSize(160, 16))
        self.label_15.setMaximumSize(QtCore.QSize(200, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_6.addWidget(self.label_15)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(16)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.parametersFrame)
        self.label_6.setMinimumSize(QtCore.QSize(160, 16))
        self.label_6.setMaximumSize(QtCore.QSize(200, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.pressureSpinBox = QtWidgets.QDoubleSpinBox(self.parametersFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pressureSpinBox.sizePolicy().hasHeightForWidth())
        self.pressureSpinBox.setSizePolicy(sizePolicy)
        self.pressureSpinBox.setMinimumSize(QtCore.QSize(80, 24))
        self.pressureSpinBox.setMaximumSize(QtCore.QSize(112, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setKerning(True)
        self.pressureSpinBox.setFont(font)
        self.pressureSpinBox.setWrapping(False)
        self.pressureSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.pressureSpinBox.setProperty("showGroupSeparator", True)
        self.pressureSpinBox.setDecimals(3)
        self.pressureSpinBox.setMinimum(0.001)
        self.pressureSpinBox.setMaximum(10000.0)
        self.pressureSpinBox.setSingleStep(0.001)
        self.pressureSpinBox.setProperty("value", 400.0)
        self.pressureSpinBox.setObjectName("pressureSpinBox")
        self.horizontalLayout_8.addWidget(self.pressureSpinBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.parametersLayout.addLayout(self.verticalLayout_6)
        self.line_2 = QtWidgets.QFrame(self.parametersFrame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.parametersLayout.addWidget(self.line_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.parametersFrame)
        self.label_11.setMinimumSize(QtCore.QSize(160, 16))
        self.label_11.setMaximumSize(QtCore.QSize(200, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(16)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.parametersFrame)
        self.label_12.setMinimumSize(QtCore.QSize(160, 16))
        self.label_12.setMaximumSize(QtCore.QSize(200, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.youngSpinBox = QtWidgets.QSpinBox(self.parametersFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.youngSpinBox.sizePolicy().hasHeightForWidth())
        self.youngSpinBox.setSizePolicy(sizePolicy)
        self.youngSpinBox.setMinimumSize(QtCore.QSize(80, 24))
        self.youngSpinBox.setMaximumSize(QtCore.QSize(112, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.youngSpinBox.setFont(font)
        self.youngSpinBox.setWrapping(False)
        self.youngSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.youngSpinBox.setProperty("showGroupSeparator", True)
        self.youngSpinBox.setMaximum(1000)
        self.youngSpinBox.setProperty("value", 71)
        self.youngSpinBox.setObjectName("youngSpinBox")
        self.horizontalLayout_12.addWidget(self.youngSpinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(16)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_13 = QtWidgets.QLabel(self.parametersFrame)
        self.label_13.setMinimumSize(QtCore.QSize(160, 16))
        self.label_13.setMaximumSize(QtCore.QSize(200, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        self.poissonSpinBox = QtWidgets.QDoubleSpinBox(self.parametersFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.poissonSpinBox.sizePolicy().hasHeightForWidth())
        self.poissonSpinBox.setSizePolicy(sizePolicy)
        self.poissonSpinBox.setMinimumSize(QtCore.QSize(80, 24))
        self.poissonSpinBox.setMaximumSize(QtCore.QSize(112, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.poissonSpinBox.setFont(font)
        self.poissonSpinBox.setWrapping(False)
        self.poissonSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.poissonSpinBox.setProperty("showGroupSeparator", True)
        self.poissonSpinBox.setDecimals(2)
        self.poissonSpinBox.setMinimum(0.01)
        self.poissonSpinBox.setMaximum(1.0)
        self.poissonSpinBox.setSingleStep(0.01)
        self.poissonSpinBox.setProperty("value", 0.33)
        self.poissonSpinBox.setObjectName("poissonSpinBox")
        self.horizontalLayout_13.addWidget(self.poissonSpinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.parametersLayout.addLayout(self.verticalLayout_4)
        self.line_3 = QtWidgets.QFrame(self.parametersFrame)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.parametersLayout.addWidget(self.line_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.parametersFrame)
        self.label_8.setMinimumSize(QtCore.QSize(160, 16))
        self.label_8.setMaximumSize(QtCore.QSize(200, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(16)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.parametersFrame)
        self.label_7.setMinimumSize(QtCore.QSize(160, 16))
        self.label_7.setMaximumSize(QtCore.QSize(200, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.horizontalCountSpinBox = QtWidgets.QSpinBox(self.parametersFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalCountSpinBox.sizePolicy().hasHeightForWidth())
        self.horizontalCountSpinBox.setSizePolicy(sizePolicy)
        self.horizontalCountSpinBox.setMinimumSize(QtCore.QSize(80, 24))
        self.horizontalCountSpinBox.setMaximumSize(QtCore.QSize(112, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.horizontalCountSpinBox.setFont(font)
        self.horizontalCountSpinBox.setWrapping(False)
        self.horizontalCountSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.horizontalCountSpinBox.setProperty("showGroupSeparator", True)
        self.horizontalCountSpinBox.setMinimum(1)
        self.horizontalCountSpinBox.setMaximum(40)
        self.horizontalCountSpinBox.setProperty("value", 12)
        self.horizontalCountSpinBox.setObjectName("horizontalCountSpinBox")
        self.horizontalLayout_9.addWidget(self.horizontalCountSpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(16)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.parametersFrame)
        self.label_10.setMinimumSize(QtCore.QSize(160, 16))
        self.label_10.setMaximumSize(QtCore.QSize(200, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.verticalCountSpinBox = QtWidgets.QSpinBox(self.parametersFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalCountSpinBox.sizePolicy().hasHeightForWidth())
        self.verticalCountSpinBox.setSizePolicy(sizePolicy)
        self.verticalCountSpinBox.setMinimumSize(QtCore.QSize(80, 24))
        self.verticalCountSpinBox.setMaximumSize(QtCore.QSize(112, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.verticalCountSpinBox.setFont(font)
        self.verticalCountSpinBox.setWrapping(False)
        self.verticalCountSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.verticalCountSpinBox.setProperty("showGroupSeparator", True)
        self.verticalCountSpinBox.setMinimum(1)
        self.verticalCountSpinBox.setMaximum(40)
        self.verticalCountSpinBox.setProperty("value", 6)
        self.verticalCountSpinBox.setObjectName("verticalCountSpinBox")
        self.horizontalLayout_11.addWidget(self.verticalCountSpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.parametersLayout.addLayout(self.verticalLayout_3)
        self.leftLayout.addWidget(self.parametersFrame)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_14.addLayout(self.horizontalLayout_16)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, -1, -1, 8)
        self.verticalLayout_7.setSpacing(12)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.createMeshPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.createMeshPushButton.setMinimumSize(QtCore.QSize(160, 32))
        self.createMeshPushButton.setMaximumSize(QtCore.QSize(200, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.createMeshPushButton.setFont(font)
        self.createMeshPushButton.setObjectName("createMeshPushButton")
        self.verticalLayout_7.addWidget(self.createMeshPushButton)
        self.makeCalculationPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.makeCalculationPushButton.setMinimumSize(QtCore.QSize(160, 32))
        self.makeCalculationPushButton.setMaximumSize(QtCore.QSize(200, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.makeCalculationPushButton.setFont(font)
        self.makeCalculationPushButton.setObjectName("makeCalculationPushButton")
        self.verticalLayout_7.addWidget(self.makeCalculationPushButton)
        self.verticalLayout_7.setStretch(0, 100)
        self.verticalLayout_7.setStretch(1, 1)
        self.verticalLayout_7.setStretch(2, 1)
        self.horizontalLayout_14.addLayout(self.verticalLayout_7)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_14.addLayout(self.horizontalLayout_15)
        self.leftLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout.addLayout(self.leftLayout)
        self.rightLayout = QtWidgets.QGridLayout()
        self.rightLayout.setSpacing(0)
        self.rightLayout.setObjectName("rightLayout")
        self.plotWidgetLayout = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidgetLayout.sizePolicy().hasHeightForWidth())
        self.plotWidgetLayout.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.plotWidgetLayout.setFont(font)
        self.plotWidgetLayout.setObjectName("plotWidgetLayout")
        self.rightLayout.addWidget(self.plotWidgetLayout, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.rightLayout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 10)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Изгиб пластины"))
        self.label_14.setText(_translate("MainWindow", "Начальные параметры пластины"))
        self.label.setText(_translate("MainWindow", "Длина (мм)"))
        self.label_3.setText(_translate("MainWindow", "Ширина (мм)"))
        self.label_4.setText(_translate("MainWindow", "Толщина (мм)"))
        self.label_15.setText(_translate("MainWindow", "Внешние силы"))
        self.label_6.setText(_translate("MainWindow", "Давление сверху (кг/м2)"))
        self.label_11.setText(_translate("MainWindow", "Свойства материала"))
        self.label_12.setText(_translate("MainWindow", "Модуль Юнга (ГПа)"))
        self.label_13.setText(_translate("MainWindow", "Коэффициент Пуассона"))
        self.label_8.setText(_translate("MainWindow", "Количество элементов"))
        self.label_7.setText(_translate("MainWindow", "По горизонтали"))
        self.label_10.setText(_translate("MainWindow", "По вертикали"))
        self.createMeshPushButton.setText(_translate("MainWindow", "Сетка"))
        self.makeCalculationPushButton.setText(_translate("MainWindow", "Расчёт"))
